<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [3]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [4]:
import folium
import pandas as pd

In [6]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

In [11]:
# Task 1: Mark all SpaceX launch sites on a map

import pandas as pd
import folium

# Step 1: Create a dataframe with launch site names and coordinates
launch_sites = pd.DataFrame({
    'LaunchSite': ['CCAFS LC-40', 'CCAFS SLC-40', 'KSC LC-39A', 'VAFB SLC-4E'],
    'Latitude': [28.562302, 28.563197, 28.573255, 34.632093],
    'Longitude': [-80.577356, -80.576820, -80.646895, -120.610829]
})

# Step 2: Create a Folium map centered at the average coordinates
site_map = folium.Map(
    location=[launch_sites['Latitude'].mean(), launch_sites['Longitude'].mean()],
    zoom_start=5
)

# Step 3: Add a marker for each launch site
for idx, row in launch_sites.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=row['LaunchSite'],
        icon=folium.Icon(color='blue', icon='rocket', prefix='fa')  # blue rocket marker
    ).add_to(site_map)

# Step 4: Display the map
site_map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [7]:
# Download and read the `spacex_launch_geo.csv`
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

In [8]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [10]:
# Start location is NASA Johnson Space Center
import pandas as pd
import folium

nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [15]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [12]:
import pandas as pd
import folium

# Define NASA coordinate (center of the map)
nasa_coordinate = [29.5593, -95.0839]

# Create the launch_sites dataframe
launch_sites = pd.DataFrame({
    'LaunchSite': ['CCAFS LC-40', 'CCAFS SLC-40', 'KSC LC-39A', 'VAFB SLC-4E'],
    'Latitude': [28.562302, 28.563197, 28.573255, 34.632093],
    'Longitude': [-80.577356, -80.576820, -80.646895, -120.610829]
})

# Initialize the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

# For each launch site, add a circle and popup
for index, row in launch_sites.iterrows():
    
    coordinate = [row['Latitude'], row['Longitude']]
    
    folium.Circle(
        location=coordinate,
        radius=1000,
        color='#d35400',
        fill=True
    ).add_child(folium.Popup(row['LaunchSite'])).add_to(site_map)

site_map

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

In [14]:
# Task 2: Mark the success/failed launches for each site on the map

import folium

# Initialize the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

# Add markers for each launch
for index, row in spacex_df.iterrows():
    
    coordinate = [row['Lat'], row['Long']]
    
    # Choose color based on launch success
    if row['class'] == 1:
        color = 'green'   # successful launch
    else:
        color = 'red'     # failed launch
    
    folium.CircleMarker(
        location=coordinate,
        radius=5,
        color=color,
        fill=True,
        fill_color=color
    ).add_child(folium.Popup(row['Launch Site'])).add_to(site_map)

site_map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [15]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [16]:
marker_cluster = MarkerCluster()

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

In [17]:

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red
# Create a new column marker_color
spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'green' if x == 1 else 'red')

# Check the result
spacex_df[['class','marker_color']].head()

   class marker_color
0      0          red
1      0          red
2      0          red
3      0          red
4      0          red

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [18]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
for index, record in spacex_df.iterrows():
    
    # create marker
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        icon=folium.Icon(
            color='white',
            icon_color=record['marker_color']
        )
    )
    
    # add marker to cluster
    marker_cluster.add_child(marker)

site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

In [19]:
# TASK 3: Calculate the distances between a launch site to its proximities
# =========================
# TASK 3: Calculate distances between launch sites and NASA Johnson Space Center
# using Haversine formula (no external packages needed)
# =========================

import pandas as pd
import math

# Step 1: Define launch sites
launch_sites = pd.DataFrame({
    'LaunchSite': ['CCAFS LC-40', 'CCAFS SLC-40', 'KSC LC-39A', 'VAFB SLC-4E'],
    'Latitude': [28.562302, 28.563197, 28.573255, 34.632093],
    'Longitude': [-80.577356, -80.576820, -80.646895, -120.610829]
})

# Step 2: Define NASA Johnson Space Center coordinates
nasa_coordinate = (29.5593, -95.0839)  # latitude, longitude

# Step 3: Haversine formula to calculate distance in km
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)
    
    a = math.sin(delta_phi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(delta_lambda/2)**2
    c = 2*math.atan2(math.sqrt(a), math.sqrt(1-a))
    
    return R * c

# Step 4: Calculate distance for each launch site
launch_sites['Distance_km'] = launch_sites.apply(
    lambda row: haversine(row['Latitude'], row['Longitude'], nasa_coordinate[0], nasa_coordinate[1]),
    axis=1
)

# Step 5: Show results
launch_sites

     LaunchSite   Latitude   Longitude  Distance_km
0   CCAFS LC-40  28.562302  -80.577356  1413.405578
1  CCAFS SLC-40  28.563197  -80.576820  1413.443551
2    KSC LC-39A  28.573255  -80.646895  1406.511241
3   VAFB SLC-4E  34.632093 -120.610829  2462.694040

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [20]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [21]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [22]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
import folium

# Reuse the Haversine function from Task 3
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)
    
    a = math.sin(delta_phi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(delta_lambda/2)**2
    c = 2*math.atan2(math.sqrt(a), math.sqrt(1-a))
    
    return R * c

# Example launch site: CCAFS LC-40
launch_site_lat = 28.562302
launch_site_lon = -80.577356

# TODO: Mark the closest coastline (example coordinates from lab)
coastline_lat = 28.56367
coastline_lon = -80.57163

# Calculate distance to the coastline
distance_coastline = haversine(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
print(f"Distance from launch site to closest coastline: {distance_coastline:.3f} km")

# Create a map centered at the launch site
m = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=15)

# Add marker for launch site
folium.Marker(
    [launch_site_lat, launch_site_lon],
    popup='CCAFS LC-40 Launch Site',
    icon=folium.Icon(color='blue', icon='rocket', prefix='fa')
).add_to(m)

# Add marker for closest coastline
folium.Marker(
    [coastline_lat, coastline_lon],
    popup=f'Closest Coastline ({distance_coastline:.3f} km away)',
    icon=folium.Icon(color='green')
).add_to(m)

# Add a line connecting launch site and coastline
folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]],
    color='red',
    weight=2,
    dash_array='5'
).add_to(m)

# Display map
m

Distance from launch site to closest coastline: 0.580 km

In [23]:
import folium
from folium.features import DivIcon
import math

# Haversine function (for distance calculation)
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)
    
    a = math.sin(delta_phi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(delta_lambda/2)**2
    c = 2*math.atan2(math.sqrt(a), math.sqrt(1-a))
    
    return R * c

# Launch site coordinate (example: CCAFS LC-40)
launch_site_coord = (28.562302, -80.577356)

# Closest coastline coordinate (example)
coastline_coord = (28.56367, -80.57163)

# Calculate distance
distance_km = haversine(launch_site_coord[0], launch_site_coord[1],
                        coastline_coord[0], coastline_coord[1])

# Create map centered at launch site
m = folium.Map(location=launch_site_coord, zoom_start=15)

# Add launch site marker
folium.Marker(
    location=launch_site_coord,
    popup='CCAFS LC-40 Launch Site',
    icon=folium.Icon(color='blue', icon='rocket', prefix='fa')
).add_to(m)

# Add closest coastline marker
folium.Marker(
    location=coastline_coord,
    popup='Closest Coastline',
    icon=folium.Icon(color='green')
).add_to(m)

# Add DivIcon marker showing the distance
distance_marker = folium.map.Marker(
    location=coastline_coord,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>{:10.2f} KM</b></div>'.format(distance_km)
    )
)
distance_marker.add_to(m)

# Optional: Draw line connecting launch site and coastline
folium.PolyLine([launch_site_coord, coastline_coord], color='red', weight=2, dash_array='5').add_to(m)

# Display map
m

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [24]:
import folium

# Example coordinates
launch_site_coord = [28.562302, -80.577356]   # CCAFS LC-40
coastline_coord = [28.56367, -80.57163]       # Closest coastline point

# Initialize map
site_map = folium.Map(location=launch_site_coord, zoom_start=15)

# Add launch site marker
folium.Marker(
    location=launch_site_coord,
    popup='CCAFS LC-40 Launch Site',
    icon=folium.Icon(color='blue', icon='rocket', prefix='fa')
).add_to(site_map)

# Add coastline marker
folium.Marker(
    location=coastline_coord,
    popup='Closest Coastline',
    icon=folium.Icon(color='green')
).add_to(site_map)

# Draw a PolyLine connecting the launch site and coastline
lines = folium.PolyLine(
    locations=[launch_site_coord, coastline_coord],
    color='red',
    weight=2,
    dash_array='5'
)

# Add the PolyLine to the map
site_map.add_child(lines)

# Display map
site_map

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [25]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site
import folium
from folium.features import DivIcon
import math

# Haversine function to calculate distance in km
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)
    
    a = math.sin(delta_phi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(delta_lambda/2)**2
    c = 2*math.atan2(math.sqrt(a), math.sqrt(1-a))
    
    return R * c

# Example launch site
launch_site_coord = [28.562302, -80.577356]  # CCAFS LC-40

# Example feature coordinate (closest city)
feature_coord = [28.56250, -80.57000]  # Replace with MousePosition coordinate

# Calculate distance
distance_feature = haversine(launch_site_coord[0], launch_site_coord[1],
                             feature_coord[0], feature_coord[1])

# Create map
m = folium.Map(location=launch_site_coord, zoom_start=15)

# Launch site marker
folium.Marker(
    location=launch_site_coord,
    popup='CCAFS LC-40 Launch Site',
    icon=folium.Icon(color='blue', icon='rocket', prefix='fa')
).add_to(m)

# Feature marker (city, railway, highway, etc.)
folium.Marker(
    location=feature_coord,
    popup='Closest City',
    icon=folium.Icon(color='green')
).add_to(m)

# Add DivIcon to display distance
distance_marker = folium.map.Marker(
    location=feature_coord,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>{:10.2f} KM</b></div>'.format(distance_feature)
    )
)
distance_marker.add_to(m)

# Draw a line between launch site and the feature
folium.PolyLine(
    locations=[launch_site_coord, feature_coord],
    color='green',
    weight=2,
    dash_array='5'
).add_to(m)

# Display map
m

In [26]:
# =========================
# TASK 3: Complete Map with Distances to Coastline, City, Railway, Highway
# =========================

import folium
from folium.features import DivIcon
import math

# -------------------------
# Haversine function
# -------------------------
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)
    
    a = math.sin(delta_phi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(delta_lambda/2)**2
    c = 2*math.atan2(math.sqrt(a), math.sqrt(1-a))
    
    return R * c

# -------------------------
# Launch site coordinate
# -------------------------
launch_site_coord = [28.562302, -80.577356]  # CCAFS LC-40

# -------------------------
# Closest points (example coordinates from MousePosition)
# -------------------------
coastline_coord = [28.56367, -80.57163]
city_coord = [28.56250, -80.57000]
railway_coord = [28.56500, -80.57850]
highway_coord = [28.56050, -80.57500]

# -------------------------
# Calculate distances
# -------------------------
distance_coastline = haversine(launch_site_coord[0], launch_site_coord[1],
                              coastline_coord[0], coastline_coord[1])

distance_city = haversine(launch_site_coord[0], launch_site_coord[1],
                          city_coord[0], city_coord[1])

distance_railway = haversine(launch_site_coord[0], launch_site_coord[1],
                             railway_coord[0], railway_coord[1])

distance_highway = haversine(launch_site_coord[0], launch_site_coord[1],
                             highway_coord[0], highway_coord[1])

# -------------------------
# Create map
# -------------------------
site_map = folium.Map(location=launch_site_coord, zoom_start=15)

# Launch site marker
folium.Marker(
    location=launch_site_coord,
    popup='CCAFS LC-40 Launch Site',
    icon=folium.Icon(color='blue', icon='rocket', prefix='fa')
).add_to(site_map)

# -------------------------
# Function to add marker with distance label
# -------------------------
def add_feature_marker(feature_coord, name, distance, color):
    # Add marker
    folium.Marker(
        location=feature_coord,
        popup=f'{name}',
        icon=folium.Icon(color=color)
    ).add_to(site_map)
    
    # Add DivIcon showing distance
    folium.map.Marker(
        location=feature_coord,
        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 12; color:#d35400;"><b>{:10.2f} KM</b></div>'.format(distance)
        )
    ).add_to(site_map)
    
    # Draw line
    folium.PolyLine(
        locations=[launch_site_coord, feature_coord],
        color=color,
        weight=2,
        dash_array='5'
    ).add_to(site_map)

# -------------------------
# Add all features
# -------------------------
add_feature_marker(coastline_coord, 'Closest Coastline', distance_coastline, 'red')
add_feature_marker(city_coord, 'Closest City', distance_city, 'green')
add_feature_marker(railway_coord, 'Closest Railway', distance_railway, 'orange')
add_feature_marker(highway_coord, 'Closest Highway', distance_highway, 'purple')

# -------------------------
# Display map
# -------------------------
site_map

In [27]:
import folium

# Example coordinates
launch_site_coord = [28.562302, -80.577356]   # CCAFS LC-40
coastline_coord = [28.56367, -80.57163]       # Closest coastline point

# Initialize map
site_map = folium.Map(location=launch_site_coord, zoom_start=15)

# Add launch site marker
folium.Marker(
    location=launch_site_coord,
    popup='CCAFS LC-40 Launch Site',
    icon=folium.Icon(color='blue', icon='rocket', prefix='fa')
).add_to(site_map)

# Add coastline marker
folium.Marker(
    location=coastline_coord,
    popup='Closest Coastline',
    icon=folium.Icon(color='green')
).add_to(site_map)

# Draw a PolyLine connecting the launch site and coastline
lines = folium.PolyLine(
    locations=[launch_site_coord, coastline_coord],
    color='red',
    weight=2,
    dash_array='5'
)

# Add the PolyLine to the map
site_map.add_child(lines)

# Display map
site_map

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>